[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "Unlicense",
  "Unicode-DFS-2016",
  "CC0-1.0",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
