name: ci
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_TOOLCHAIN_VERSION: stable

# TODO caching (dprint exe, rust files, sccache)
# TODO musl build, static link for msvc
# TODO test coverage
# TODO release (arm macos-14)
# TODO lock file?

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-12
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - run: rustup toolchain install --profile minimal ${{ env.RUST_TOOLCHAIN_VERSION }}
      - run: rustup default ${{ env.RUST_TOOLCHAIN_VERSION }}
      - uses: actions/checkout@v4

      - name: fetch
        run: cargo fetch

      - if: runner.os == 'Linux'
        uses: ./.github/actions/lint

      - name: build
        run: cargo build --all-targets --all-features
      - name: test
        run: cargo test --all-features
